language: scala

jdk:
  - oraclejdk8

sudo: false

addons:
    apt:
        packages:
            - gcc-multilib
            - g++-multilib
            - libstdc++6:i386
            - libgcc1:i386
            - zlib1g:i386
            - libncurses5:i386

scala:
    - 2.11.8

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "*.lock" | xargs rm

cache:
    directories:
        - $HOME/.ivy2
        - $HOME/.sbt

android:
    components:
        - tools
        - build-tools-25.0.2
        - extra-android-m2repository
        - extra-google-m2repository

install:
    - ./travis-ci/setup.sh
    - export NDK_CCACHE=ccache
    - export ARCH=`uname -m`
    - export ANDROID_NDK_HOME=$HOME/.android/android-ndk-r14b
    - export ANDROID_HOME=$HOME/.android/android-sdk-linux
    - export PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
    - cp local.properties.travis local.properties

script:
    - sbt native-build android:package-release

deploy:
   provider: releases 
   file: "/home/travis/build/JohnFreeman9/shadowsocksr-android/target/android/output/shadowsocksr-release.apk"
   skip_cleanup: true
   api-key:
    secure: "x/IaqNQrXfhxUhlF+vvShmTdwsFPm/1tywqCG5FAWNKg6QKfq630bz9kFVX+Skf3pJhjcMWdcbWZdsltIpx/QqbCH6Hi8p5wI7vTgYyKjD/SnjF4AtMuGlM/06xqmCbzAhe2IJjGw5TwMuYx/wpC27nXPlbEKTRfviHI2W+4WwZrGsOPg0a5NshyYN5a014SOFB96Xfl+pDenHOzV0jChlrYZdA8Ep7ZdA/Yqz6HqlOQNuxHpWrxBKtK5CimXmlFfOHY7dx6ZLKR4vdWP6nvjszdJhlT8QPXNWUtx/c0we9nVHndnOMs+OKaSvUX7lBXWRodNA/hw7WV2QoQQrzSylRe+uiEJn7+S1f0AzRocNDecjlSUlwTozyuXp7hWg0284wRsF7Ph/NjKGbI+KFgtI0OWVtbnpIIlS+xGlU87f1P8AM9p0kVyx7kL5gJPAEyouZ7N6Ln/0rmk+O3L7c4eUdSkiFlQwLTlVdr41Tq8O3aVyDLRUZOa4xsth7BnfZbtJx4BRZrkP/r1aQd3tVWNhEsCRLfFzHlAJvFNpTNKSGlxWyYOubUKmzjbu5cJe5ML+Q7QGZRrkkQkBHjwhJ8qLHJeLpEI0Ba46OmyyAT5IJNJqaxg1j424wrliYE86vbCuGJGUTcSjurO0ShAJde71tqhBu6E88iqf5Wii0KkAw="
   on:
    repo: JohnFreeman9/shadowsocksr-android
    branch: nokcp